COLORS = (
        ('HOTPINK', 'pink'),
        ('DARKSEAGREEN', 'light green'),
        ('SEAGREEN', 'green'),
        ('FORESTGREEN', 'vegetable'),
        ('DARKOLIVEGREEN', 'olive green'),
        ('TEAL','teal'),
        ('LIGHTBLUE', 'light blue'),
        ('DODGERBLUE', 'blue'),
        ('DARKBLUE', 'dark blue'),
        ('CADETBLUE', 'cadet blue'),
        ('ORANGE', 'light orange'),
        ('TOMATO', 'tomato'),
        ('ORANGERED', 'dark orange'),
        ('PLUM', 'light purple'),
        ('MEDIUMPURPLE', 'purple'),
        ('REBECCAPURPLE', 'dark purple'),
        ('RED', 'red'),
        ('SALMON', 'salmon'),
        ('DARKRED', 'dark red'),
)
